name: Deployment to Production
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Deployment Process
    runs-on: ubuntu-latest
    environment: DigitalOcean
    steps:
      - name: Build
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
      - name: Run build
        run: GOOS=linux GOARCH=amd64 go build -o go_als.zone_new
      - name: Run vet
        run: go vet
      - name: Copy Executable
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY_ED25519 }}
          source: "go_als.zone_new"
          target: "/home/goals_zone/go_als.zone"
      - name: Restart application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY_ED25519 }}
          port: ${{ secrets.PORT }}
          script: ./deploy_go.sh
